// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Uplay.Persistence.Data;

#nullable disable

namespace Uplay.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250103120136_mig_19")]
    partial class mig_19
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OnwerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tin")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OnwerId");

                    b.ToTable("Branchs", "Company");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.BranchCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BranchCategories", "Company");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.BranchQrCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppFileId")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("operationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppFileId");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchQrCodes", "Company");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<int>("BranchCount")
                        .HasColumnType("integer");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OnwerId")
                        .HasColumnType("integer");

                    b.Property<string>("Tin")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("OnwerId");

                    b.ToTable("Companies", "Company");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.CompanyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyBranchs", "Company");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Abouts", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.AboutFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AboutId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.HasIndex("FileId");

                    b.ToTable("AboutFiles", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.AboutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AboutId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.HasIndex("FileId");

                    b.ToTable("AboutTypes", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Categories", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsARead")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Contacts", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Faqs", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("FeedbackTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("FeedbackTypeId");

                    b.ToTable("Feedbacks", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Partners", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.PublicReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("PublicReviews", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Reviews", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialLinks", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.YouBusines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("YouBusineses", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landings.FeedbackType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FeedbackTypes", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landings.RatingBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("RatingBranchs", "Landing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Miscs.AppFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Size")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppFiles", "Misc");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Miscs.BranchQrRetention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("QrRetCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchQrRetentions", "Misc");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.PlayLists.PlayList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("FileId");

                    b.ToTable("PlayLists", "PlayList");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.PlayLists.PlayListStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayListId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayListId");

                    b.ToTable("PlayListStatusHistories", "PlayList");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Pricings.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<double>("MonthDiscount")
                        .HasColumnType("double precision");

                    b.Property<double>("Monthly")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("PricingTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PricingTypeId");

                    b.ToTable("Pricings", "Pricing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Pricings.PricingSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PricingId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PricingId");

                    b.ToTable("PricingSections", "Pricing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Pricings.PricingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PricingTypes", "Pricing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Claims", "User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1738),
                            Deleted = false,
                            Name = "About_Post"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1757),
                            Deleted = false,
                            Name = "About_Put"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1770),
                            Deleted = false,
                            Name = "Branch_Delete"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1782),
                            Deleted = false,
                            Name = "Branch_Disable"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1791),
                            Deleted = false,
                            Name = "Category_Post"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1803),
                            Deleted = false,
                            Name = "Branch_Statistics_Get"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1814),
                            Deleted = false,
                            Name = "Branch_Qr_Retention_Get"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1823),
                            Deleted = false,
                            Name = "Contact_Get"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1833),
                            Deleted = false,
                            Name = "Contact_Details"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1842),
                            Deleted = false,
                            Name = "Faq_Post"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1854),
                            Deleted = false,
                            Name = "Faq_Put"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1863),
                            Deleted = false,
                            Name = "Faq_Delete"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1872),
                            Deleted = false,
                            Name = "FeedbackType_Post"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1880),
                            Deleted = false,
                            Name = "FeedbackType_Delete"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1888),
                            Deleted = false,
                            Name = "FeedbackType_Put"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1900),
                            Deleted = false,
                            Name = "Partner_Post"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1909),
                            Deleted = false,
                            Name = "Partner_Delete"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1916),
                            Deleted = false,
                            Name = "Partner_Put"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1924),
                            Deleted = false,
                            Name = "Playlist_Put"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1977),
                            Deleted = false,
                            Name = "PublicReview_Post"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1987),
                            Deleted = false,
                            Name = "PublicReview_Delete"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(1995),
                            Deleted = false,
                            Name = "PublicReview_Put"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(2003),
                            Deleted = false,
                            Name = "Service_Post"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(2012),
                            Deleted = false,
                            Name = "Service_Delete"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(2020),
                            Deleted = false,
                            Name = "Service_Put"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(2030),
                            Deleted = false,
                            Name = "SocialLink_Post"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(2040),
                            Deleted = false,
                            Name = "SocialLink_Put"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(2049),
                            Deleted = false,
                            Name = "Company_Delete"
                        });
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles", "User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(5531),
                            Deleted = false,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(5547),
                            Deleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(5562),
                            Deleted = false,
                            Name = "Operator"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(5572),
                            Deleted = false,
                            Name = "Company"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(5580),
                            Deleted = false,
                            Name = "Branch"
                        });
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimId = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3494),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimId = 2,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3499),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClaimId = 3,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3501),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClaimId = 4,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3503),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            ClaimId = 5,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3505),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ClaimId = 6,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3508),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClaimId = 7,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3510),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClaimId = 8,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3587),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            ClaimId = 9,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3590),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            ClaimId = 10,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3592),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            ClaimId = 11,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3594),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            ClaimId = 12,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3596),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            ClaimId = 13,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3598),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            ClaimId = 14,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3599),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            ClaimId = 15,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3601),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            ClaimId = 16,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3603),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            ClaimId = 17,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3607),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            ClaimId = 18,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3610),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            ClaimId = 19,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3611),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            ClaimId = 20,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3613),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            ClaimId = 21,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3615),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            ClaimId = 22,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3617),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            ClaimId = 23,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3619),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            ClaimId = 24,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3620),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            ClaimId = 25,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3622),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            ClaimId = 26,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3624),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            ClaimId = 27,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3625),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            ClaimId = 28,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3627),
                            Deleted = false,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            ClaimId = 1,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3629),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            ClaimId = 20,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3631),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            ClaimId = 5,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3632),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            ClaimId = 6,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3634),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            ClaimId = 23,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3693),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            ClaimId = 7,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3695),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            ClaimId = 8,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3697),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            ClaimId = 26,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3699),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            ClaimId = 9,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3701),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            ClaimId = 10,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3703),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            ClaimId = 13,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3704),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            ClaimId = 16,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3706),
                            Deleted = false,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            ClaimId = 6,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3708),
                            Deleted = false,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            ClaimId = 7,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3710),
                            Deleted = false,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 43,
                            ClaimId = 8,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3712),
                            Deleted = false,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            ClaimId = 9,
                            CreatedDate = new DateTime(2025, 1, 3, 12, 1, 36, 493, DateTimeKind.Utc).AddTicks(3713),
                            Deleted = false,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OtpCode")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "User");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", "User");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.Branch", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Users.User", "Onwer")
                        .WithMany("Branches")
                        .HasForeignKey("OnwerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onwer");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.BranchCategory", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("BranchCategories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Landing.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.BranchQrCode", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "AppFile")
                        .WithMany()
                        .HasForeignKey("AppFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("BranchQrCodes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppFile");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.Company", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Users.User", "Onwer")
                        .WithMany("Companies")
                        .HasForeignKey("OnwerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Onwer");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.CompanyBranch", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("CompanyBranches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Company", "Company")
                        .WithMany("CompanyBranchs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.AboutFile", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Landing.About", "About")
                        .WithMany("AboutFiles")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.AboutType", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Landing.About", null)
                        .WithMany("AboutTypes")
                        .HasForeignKey("AboutId");

                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Category", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Feedback", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("Feedbacks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Landings.FeedbackType", "FeedbackType")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FeedbackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("FeedbackType");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Partner", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.PublicReview", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Review", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("Reviews")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.Service", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Landing.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.YouBusines", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landings.RatingBranch", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("RatingBranchs")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Miscs.BranchQrRetention", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.PlayLists.PlayList", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Companies.Branch", "Branch")
                        .WithMany("PlayLists")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Miscs.AppFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.PlayLists.PlayListStatusHistory", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.PlayLists.PlayList", "PlayList")
                        .WithMany("PlayListStatusHistories")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayList");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Pricings.Pricing", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Pricings.PricingType", "PricingType")
                        .WithMany()
                        .HasForeignKey("PricingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingType");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Pricings.PricingSection", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Pricings.Pricing", "Pricing")
                        .WithMany("PricingSections")
                        .HasForeignKey("PricingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pricing");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.RoleClaim", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Users.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Users.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.UserRole", b =>
                {
                    b.HasOne("Uplay.Domain.Entities.Models.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uplay.Domain.Entities.Models.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.Branch", b =>
                {
                    b.Navigation("BranchCategories");

                    b.Navigation("BranchQrCodes");

                    b.Navigation("CompanyBranches");

                    b.Navigation("Feedbacks");

                    b.Navigation("PlayLists");

                    b.Navigation("RatingBranchs");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Companies.Company", b =>
                {
                    b.Navigation("CompanyBranchs");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landing.About", b =>
                {
                    b.Navigation("AboutFiles");

                    b.Navigation("AboutTypes");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Landings.FeedbackType", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.PlayLists.PlayList", b =>
                {
                    b.Navigation("PlayListStatusHistories");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Pricings.Pricing", b =>
                {
                    b.Navigation("PricingSections");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Uplay.Domain.Entities.Models.Users.User", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Companies");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
